# wrangler.toml
# Konfigurasi untuk Cloudflare Pages / Workers

name = "report-pedo-web"
main = "_worker.js"
compatibility_date = "2024-12-01"

[[pages]]
    build_command = ""
    destination = "/"

# Env variables (optional)
# [vars]
# SECRET_KEY = "your-secret-key"

# Routes
# [[routes]]
# pattern = "report.mryagami.com/*"
# zone_id = "your-zone-id"
